# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poets_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PoetsGroup'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Visible for other users'), ('DRAFT', 'Visible just for me')], default='PUB', max_length=5),
        ),
    ]
