# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160831_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Visible for other users'), ('DRAFT', 'Visible just for me (in the draft view)')], default='PUB', max_length=5),
        ),
        migrations.AlterField(
            model_name='poetsgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
