# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160902_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetsgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='poetsgroup',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Public Site'), ('PRIV', 'Private Site'), ('CONF', 'Confidential Site')], default='PUB', max_length=4),
        ),
    ]
